### ISSUE TITLE
Issue getting bulid

### ISSUE THREAD

**Issue by ghost** [gabrielemariotti/colorpickercollection#3]
I have used git url as mentioned in the document. While run the my application build getting following error.
Error:A problem occurred configuring project ':app'.

> Artifact 'colorpickercollection.jar (com.github.gabrielemariotti:colorpickercollection:v1.1.0)' not found.
>   Searched in the following locations:
>       https://jitpack.io/com/github/gabrielemariotti/colorpickercollection/v1.0/colorpickercollection-v1.0.jar

Could you please let me know is the issue.

**Comment by gabrielemariotti** [comment]
Check #4
